"""RankForge — Streamlit demo UI.

Run locally:
    streamlit run app/streamlit_app.py
"""
from __future__ import annotations

import json
import sys
import time
from pathlib import Path

import streamlit as st

REPO = Path(__file__).resolve().parents[1]
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))


# ─────────────────────────────────────────────────────────────────────────────
# Page setup
# ─────────────────────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="RankForge",
    page_icon="🔍",
    layout="wide",
    initial_sidebar_state="expanded",
)


# ─────────────────────────────────────────────────────────────────────────────
# Cached resource loaders
# ─────────────────────────────────────────────────────────────────────────────
@st.cache_resource(show_spinner="Loading retrievers + rankers (first time may take ~30 s)…")
def load_resources():
    """Load all retrievers and rankers exactly once per process."""
    from src.ranking.ranker import LightGBMRanker
    from src.ranking.two_stage import TwoStageRanker
    from src.retrieval.bm25_retriever import BM25Retriever
    from src.retrieval.hybrid_retriever import HybridRetriever
    from src.retrieval.vector_retriever import VectorRetriever

    bm25 = BM25Retriever()
    vector = VectorRetriever()
    hybrid = HybridRetriever(bm25=bm25, vector=vector)
    ranker = LightGBMRanker()
    two_stage = TwoStageRanker(lgbm=ranker)

    # Warm caches: triggers model downloads / pickle loads now, not on first query.
    bm25.search("warmup", top_k=1)
    vector.search("warmup", top_k=1)

    return {
        "bm25": bm25,
        "vector": vector,
        "hybrid": hybrid,
        "ranker": ranker,
        "two_stage": two_stage,
    }


@st.cache_data(show_spinner=False)
def load_corpus_map() -> dict[str, dict]:
    docs: dict[str, dict] = {}
    for line in (REPO / "data" / "corpus.jsonl").read_text().splitlines():
        if line.strip():
            d = json.loads(line)
            docs[d["doc_id"]] = d
    return docs


@st.cache_data(show_spinner=False)
def load_categories() -> dict[str, list[str]]:
    from src.corpus.ontology import CATEGORIES
    return {cat: list(topics) for cat, topics in CATEGORIES.items()}


# ─────────────────────────────────────────────────────────────────────────────
# Search dispatch
# ─────────────────────────────────────────────────────────────────────────────
def run_all_setups(resources: dict, query: str, top_k: int, *, run_ce: bool):
    """Return ({setup_name: [(doc_id, score), ...]}, {setup_name: latency_ms})."""
    results: dict[str, list[tuple[str, float]]] = {}
    latencies: dict[str, float] = {}

    t = time.perf_counter()
    bm25 = resources["bm25"].search(query, top_k=top_k)
    latencies["BM25"] = (time.perf_counter() - t) * 1000
    results["BM25"] = bm25

    t = time.perf_counter()
    vec = resources["vector"].search(query, top_k=top_k)
    latencies["FAISS (vector)"] = (time.perf_counter() - t) * 1000
    results["FAISS (vector)"] = vec

    t = time.perf_counter()
    hyb = resources["hybrid"].search(query, top_k=top_k, per_retriever=50)
    latencies["Hybrid (RRF)"] = (time.perf_counter() - t) * 1000
    results["Hybrid (RRF)"] = [(c.doc_id, c.rrf_score) for c in hyb]

    t = time.perf_counter()
    rank = resources["ranker"].rank(query, top_k=top_k)
    latencies["LightGBM Ranker"] = (time.perf_counter() - t) * 1000
    results["LightGBM Ranker"] = [(c.doc_id, float(s)) for c, s in rank]

    if run_ce:
        t = time.perf_counter()
        ce = resources["two_stage"].rank(query, top_k=top_k)
        latencies["+ Cross-Encoder"] = (time.perf_counter() - t) * 1000
        results["+ Cross-Encoder"] = [(item.candidate.doc_id, item.ce_score) for item in ce]

    return results, latencies


# ─────────────────────────────────────────────────────────────────────────────
# UI
# ─────────────────────────────────────────────────────────────────────────────
resources = load_resources()
corpus = load_corpus_map()
categories = load_categories()

st.title("🔍 RankForge")
st.caption(
    "Hybrid search & learning-to-rank · BM25 + FAISS + LightGBM LambdaRank + MS MARCO Cross-Encoder · "
    f"{len(corpus):,} docs across {len(categories)} categories"
)

with st.sidebar:
    st.header("📚 What's in the corpus")
    st.caption(
        "All documents are synthetic, generated by an LLM over the taxonomy below. "
        "Queries that match these topics will return useful results; off-topic queries will not."
    )
    for cat, topics in categories.items():
        with st.expander(cat):
            for topic in topics:
                st.markdown(f"- {topic}")

    st.divider()
    st.subheader("Settings")
    top_k = st.slider("Top-K results per setup", 5, 20, 10)
    run_ce = st.checkbox(
        "Include cross-encoder rerank",
        value=True,
        help="Adds a slow neural reranking stage (~1.5 s per query) on top of LightGBM's top-20.",
    )
    body_chars = st.slider("Body excerpt length", 100, 600, 280, 20)


# ── Search bar ────────────────────────────────────────────────────────────
EXAMPLES = [
    "how to reduce LLM inference cost",
    "ways to make AI API cheaper",
    "consensus algorithms for distributed databases",
    "kubernetes blue-green deployment",
    "value investing strategies",
    "Italian pasta basics",
]

if "query" not in st.session_state:
    st.session_state.query = ""

col_q, col_btn = st.columns([5, 1])
with col_q:
    query = st.text_input(
        "Search",
        value=st.session_state.query,
        placeholder="how to reduce LLM inference cost",
        label_visibility="collapsed",
    )
with col_btn:
    run = st.button("Search", type="primary", use_container_width=True)

with st.expander("💡 Example queries", expanded=False):
    cols = st.columns(3)
    for i, ex in enumerate(EXAMPLES):
        with cols[i % 3]:
            if st.button(ex, key=f"example_{i}", use_container_width=True):
                st.session_state.query = ex
                st.rerun()


# ── Results ───────────────────────────────────────────────────────────────
if (run or query) and query:
    with st.spinner("Running retrieval + ranking pipelines…"):
        results, latencies = run_all_setups(resources, query, top_k, run_ce=run_ce)

    # Latency strip
    cols = st.columns(len(latencies))
    for col, (name, ms) in zip(cols, latencies.items()):
        col.metric(name, f"{ms:.0f} ms")

    st.divider()

    # Results in tabs
    tabs = st.tabs(list(results.keys()))
    for tab, (setup, items) in zip(tabs, results.items()):
        with tab:
            if not items:
                st.info("No results.")
                continue
            for rank, (doc_id, score) in enumerate(items, 1):
                d = corpus.get(doc_id, {})
                title = d.get("title", "(untitled)")
                category = d.get("category", "")
                topic = d.get("topic", "")
                body = d.get("body", "") or ""
                hard_neg_badge = "  🚧 hard-neg" if d.get("is_hard_negative") else ""
                excerpt = (body[:body_chars] + "…") if len(body) > body_chars else body

                with st.container(border=True):
                    head_l, head_r = st.columns([5, 1])
                    with head_l:
                        st.markdown(f"**#{rank} · {title}**{hard_neg_badge}")
                        st.caption(f"`{doc_id}` · {category} → {topic}")
                    with head_r:
                        st.metric("score", f"{score:.3f}")
                    st.markdown(excerpt)
elif query == "" and run:
    st.warning("Type a query above to search.")


# ── Footer ────────────────────────────────────────────────────────────────
st.divider()
st.caption(
    "Built with [BM25](https://en.wikipedia.org/wiki/Okapi_BM25), "
    "[FAISS](https://faiss.ai), "
    "[LightGBM LambdaRank](https://lightgbm.readthedocs.io/), "
    "and [MS MARCO Cross-Encoder](https://huggingface.co/cross-encoder/ms-marco-MiniLM-L-6-v2). "
    "Source: [github.com/avszoom/RankForge](https://github.com/avszoom/RankForge)."
)
