[theme]
primaryColor = "#FF6F2C"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F4F4F4"
textColor = "#1F1F1F"

[server]
headless = true
runOnSave = true
maxUploadSize = 50

[browser]
gatherUsageStats = false
